# Generated by Django 4.1.7 on 2023-02-19 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=50, null=True, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, help_text='Наименование категории', max_length=200, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.TextField(blank=True, help_text='Ссылка на изображение', max_length=500, null=True, verbose_name='Ссылка на изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goods', to='webapp.categories', verbose_name='Товар')),
            ],
        ),
    ]
