# Generated by Django 4.1.7 on 2023-02-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_goods_products_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='webapp.categories', verbose_name='Категория'),
        ),
    ]
