# Generated by Django 4.1.7 on 2023-02-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.CharField(blank=True, help_text='Описание категории', max_length=200, null=True, verbose_name='Описание'),
        ),
    ]
